// ── Static suggestion data ────────────────────────────────────────────────────

const businessSuggestions = [
    { text: 'Dentist in New York', cat: 'USA' },
    { text: 'Restaurant in Los Angeles', cat: 'USA' },
    { text: 'Real Estate Agency in Miami', cat: 'USA' },
    { text: 'Software House in San Francisco', cat: 'USA' },
    { text: 'Gym in Chicago', cat: 'USA' },
    { text: 'Lawyer in Houston', cat: 'USA' },
    { text: 'E-commerce Store in Seattle', cat: 'USA' },
    { text: 'Spa in Las Vegas', cat: 'USA' },
    { text: 'Auto Repair in Dallas', cat: 'USA' },
    { text: 'Medical Clinic in Boston', cat: 'USA' },
    { text: 'Dentist in London', cat: 'UK' },
    { text: 'Restaurant in Manchester', cat: 'UK' },
    { text: 'Real Estate Agency in Birmingham', cat: 'UK' },
    { text: 'Software House in Edinburgh', cat: 'UK' },
    { text: 'Gym in Glasgow', cat: 'UK' },
    { text: 'Lawyer in Leeds', cat: 'UK' },
    { text: 'E-commerce Store in Bristol', cat: 'UK' },
    { text: 'Spa in Liverpool', cat: 'UK' },
    { text: 'Auto Repair in Newcastle', cat: 'UK' },
    { text: 'Medical Clinic in Sheffield', cat: 'UK' },
    { text: 'Dentist in Berlin', cat: 'DE' },
    { text: 'Restaurant in Munich', cat: 'DE' },
    { text: 'Real Estate Agency in Frankfurt', cat: 'DE' },
    { text: 'Software House in Hamburg', cat: 'DE' },
    { text: 'Gym in Cologne', cat: 'DE' },
    { text: 'Lawyer in Stuttgart', cat: 'DE' },
    { text: 'E-commerce Store in Düsseldorf', cat: 'DE' },
    { text: 'Spa in Leipzig', cat: 'DE' },
    { text: 'Auto Repair in Dortmund', cat: 'DE' },
    { text: 'Medical Clinic in Bremen', cat: 'DE' },
    { text: 'Dentist in Dubai', cat: 'UAE' },
    { text: 'Restaurant in Dubai Marina', cat: 'UAE' },
    { text: 'Real Estate Agency in Downtown Dubai', cat: 'UAE' },
    { text: 'Software House in Dubai Silicon Oasis', cat: 'UAE' },
    { text: 'Gym in Jumeirah', cat: 'UAE' },
    { text: 'Lawyer in Business Bay', cat: 'UAE' },
    { text: 'E-commerce Store in Dubai Internet City', cat: 'UAE' },
    { text: 'Spa in Palm Jumeirah', cat: 'UAE' },
    { text: 'Auto Repair in Al Quoz', cat: 'UAE' },
    { text: 'Medical Clinic in Deira', cat: 'UAE' },
    { text: 'Software House in Karachi', cat: 'PK' },
    { text: 'Software House in Lahore', cat: 'PK' },
    { text: 'Software House in Islamabad', cat: 'PK' },
    { text: 'Software House in Rawalpindi', cat: 'PK' },
    { text: 'Software House in Faisalabad', cat: 'PK' },
    { text: 'Software House in Multan', cat: 'PK' },
    { text: 'Software House in Peshawar', cat: 'PK' },
    { text: 'Software House in Quetta', cat: 'PK' },
    { text: 'Software House in Sialkot', cat: 'PK' },
    { text: 'Software House in Gujranwala', cat: 'PK' },
    { text: 'Software House in Hyderabad', cat: 'PK' },
    { text: 'Software House in Sargodha', cat: 'PK' },
    { text: 'Software House in Bahawalpur', cat: 'PK' },
    { text: 'Software House in Sukkur', cat: 'PK' },
    { text: 'Software House in Abbottabad', cat: 'PK' },
    { text: 'Software House in Mardan', cat: 'PK' },
    { text: 'Software House in Gujrat', cat: 'PK' },
    { text: 'Software House in Sahiwal', cat: 'PK' },
    { text: 'Software House in Larkana', cat: 'PK' },
    { text: 'Software House in Sheikhupura', cat: 'PK' },
    { text: 'Dentist in Karachi', cat: 'PK' },
    { text: 'Dentist in Lahore', cat: 'PK' },
    { text: 'Restaurant in Islamabad', cat: 'PK' },
    { text: 'Real Estate Agency in Lahore', cat: 'PK' },
    { text: 'Gym in Karachi', cat: 'PK' },
    { text: 'E-commerce Store in Islamabad', cat: 'PK' },
    { text: 'Spa in Lahore', cat: 'PK' },
    { text: 'Roofing Contractor in New Jersey', cat: 'SEO' },
    { text: 'HVAC Services in Florida', cat: 'SEO' },
    { text: 'Plumber in London', cat: 'SEO' },
    { text: 'Cosmetic Surgeon in Dubai', cat: 'SEO' },
    { text: 'Orthodontist in Berlin', cat: 'SEO' },
    { text: 'Solar Panel Installer in California', cat: 'SEO' },
    { text: 'Landscaping Company in Texas', cat: 'SEO' },
    { text: 'Interior Designer in Paris', cat: 'SEO' },
    { text: 'Wedding Photographer in Rome', cat: 'SEO' },
    { text: 'Pet Grooming in Sydney', cat: 'SEO' },
    { text: 'Veterinary Clinic in Toronto', cat: 'SEO' },
    { text: 'Accounting Firm in Tokyo', cat: 'SEO' },
    { text: 'Financial Advisor in Zurich', cat: 'SEO' },
    { text: 'Personal Trainer in Vancouver', cat: 'SEO' },
    { text: 'Pest Control in Phoenix', cat: 'SEO' },
    { text: 'Moving Company in Denver', cat: 'SEO' },
    { text: 'Locksmith in Chicago', cat: 'SEO' },
    { text: 'Yoga Studio in Bali', cat: 'SEO' },
    { text: 'Home Security in Atlanta', cat: 'SEO' },
    { text: 'Window Cleaning in Austin', cat: 'SEO' },
    { text: 'Electrician in Manchester', cat: 'SEO' },
    { text: 'Painter in Birmingham', cat: 'SEO' },
    { text: 'Pool Cleaning in Miami', cat: 'SEO' },
    { text: 'Tree Removal in Seattle', cat: 'SEO' },
    { text: 'Family Lawyer in Houston', cat: 'SEO' },
    { text: 'Personal Injury Lawyer in NY', cat: 'SEO' },
    { text: 'Chiropractor in Portland', cat: 'SEO' },
    { text: 'Physical Therapist in Calgary', cat: 'SEO' },
    { text: 'Acupuncture in San Francisco', cat: 'SEO' },
    { text: 'Dermatologist in Barcelona', cat: 'SEO' },
    { text: 'Home Health Care in Florida', cat: 'SEO' },
    { text: 'Storage Units in Vegas', cat: 'SEO' },
    { text: 'Janitorial Services in DC', cat: 'SEO' },
    { text: 'Car Detailing in Atlanta', cat: 'SEO' },
    { text: 'Auto Body Shop in Detroit', cat: 'SEO' },
    { text: 'Car Rental in Dubai', cat: 'UAE' },
    { text: 'Luxury Watch Repair in New York', cat: 'PREMIUM' },
    { text: 'Yacht Charter in Miami', cat: 'PREMIUM' },
    { text: 'Catering Service in Chicago', cat: 'EVENTS' },
    { text: 'Bakery in Paris', cat: 'FOOD' },
    { text: 'Coffee Shop in Seattle', cat: 'FOOD' },
    { text: 'Wine Shop in Napa Valley', cat: 'FOOD' },
    { text: 'Pet Hotel in Los Angeles', cat: 'PETS' },
    { text: 'Co-working Space in Berlin', cat: 'B2B' },
    { text: 'Marketing Agency in London', cat: 'B2B' },
    { text: 'Consulting Firm in Singapore', cat: 'B2B' },
    { text: 'Dance Studio in Los Angeles', cat: 'ARTS' },
    { text: 'Music School in Vienna', cat: 'ARTS' },
    { text: 'Martial Arts School in Tokyo', cat: 'SPORTS' },
    { text: 'Golf Course in Scotland', cat: 'SPORTS' },
    { text: 'Hair Salon in Paris', cat: 'BEAUTY' },
    { text: 'Barber Shop in Brooklyn', cat: 'BEAUTY' },
    { text: 'Nail Salon in Tokyo', cat: 'BEAUTY' },
    { text: 'Spa in Bali', cat: 'BEAUTY' },
    { text: 'Massage Therapy in Zurich', cat: 'HEALTH' },
    { text: 'App Development in Bangalore', cat: 'TECH' },
    { text: 'Cybersecurity Firm in Tel Aviv', cat: 'TECH' },
    { text: 'AI Startup in San Francisco', cat: 'TECH' },
    { text: 'Roofing in Florida', cat: 'HOME' },
    { text: 'Landscaping in Arizona', cat: 'HOME' },
    { text: 'Plumbing in Manchester', cat: 'HOME' },
    { text: 'HVAC in Texas', cat: 'HOME' },
    { text: 'Electrician in Birmingham', cat: 'HOME' },
];

const BUSINESS_NICHES = [
    { label: 'Software House', cat: 'Tech' },
    { label: 'Web Development Agency', cat: 'Tech' },
    { label: 'Mobile App Development', cat: 'Tech' },
    { label: 'IT Consulting Firm', cat: 'Tech' },
    { label: 'Cybersecurity Company', cat: 'Tech' },
    { label: 'Digital Marketing Agency', cat: 'Tech' },
    { label: 'SEO Agency', cat: 'Tech' },
    { label: 'AI Startup', cat: 'Tech' },
    { label: 'Data Analytics Firm', cat: 'Tech' },
    { label: 'Cloud Solutions Provider', cat: 'Tech' },
    { label: 'E-commerce Agency', cat: 'Tech' },
    { label: 'UI/UX Design Studio', cat: 'Tech' },
    { label: 'Game Development Studio', cat: 'Tech' },
    { label: 'Blockchain Company', cat: 'Tech' },
    { label: 'Dentist', cat: 'Health' },
    { label: 'Medical Clinic', cat: 'Health' },
    { label: 'Pharmacy', cat: 'Health' },
    { label: 'Physiotherapy Clinic', cat: 'Health' },
    { label: 'Chiropractic Clinic', cat: 'Health' },
    { label: 'Dermatologist', cat: 'Health' },
    { label: 'Eye Clinic', cat: 'Health' },
    { label: 'Orthodontist', cat: 'Health' },
    { label: 'Pediatric Clinic', cat: 'Health' },
    { label: 'Mental Health Clinic', cat: 'Health' },
    { label: 'Veterinary Clinic', cat: 'Health' },
    { label: 'Acupuncture Clinic', cat: 'Health' },
    { label: 'Law Firm', cat: 'Legal' },
    { label: 'Family Lawyer', cat: 'Legal' },
    { label: 'Immigration Lawyer', cat: 'Legal' },
    { label: 'Personal Injury Lawyer', cat: 'Legal' },
    { label: 'Accounting Firm', cat: 'Finance' },
    { label: 'Tax Consultancy', cat: 'Finance' },
    { label: 'Financial Advisor', cat: 'Finance' },
    { label: 'Insurance Agency', cat: 'Finance' },
    { label: 'Mortgage Broker', cat: 'Finance' },
    { label: 'Real Estate Agency', cat: 'Property' },
    { label: 'Property Management', cat: 'Property' },
    { label: 'Interior Design Studio', cat: 'Property' },
    { label: 'Architectural Firm', cat: 'Property' },
    { label: 'Construction Company', cat: 'Property' },
    { label: 'Home Renovation Company', cat: 'Property' },
    { label: 'Tutoring Center', cat: 'Education' },
    { label: 'Language School', cat: 'Education' },
    { label: 'Driving School', cat: 'Education' },
    { label: 'Music School', cat: 'Education' },
    { label: 'Coding Bootcamp', cat: 'Education' },
    { label: 'Restaurant', cat: 'Food' },
    { label: 'Cafe', cat: 'Food' },
    { label: 'Bakery', cat: 'Food' },
    { label: 'Catering Service', cat: 'Food' },
    { label: 'Juice Bar', cat: 'Food' },
    { label: 'Cloud Kitchen', cat: 'Food' },
    { label: 'Hair Salon', cat: 'Beauty' },
    { label: 'Barber Shop', cat: 'Beauty' },
    { label: 'Nail Salon', cat: 'Beauty' },
    { label: 'Spa', cat: 'Beauty' },
    { label: 'Massage Therapy Center', cat: 'Beauty' },
    { label: 'Yoga Studio', cat: 'Beauty' },
    { label: 'Gym', cat: 'Beauty' },
    { label: 'Personal Trainer', cat: 'Beauty' },
    { label: 'Clothing Store', cat: 'Retail' },
    { label: 'Electronics Store', cat: 'Retail' },
    { label: 'Jewelry Store', cat: 'Retail' },
    { label: 'Furniture Store', cat: 'Retail' },
    { label: 'Bookstore', cat: 'Retail' },
    { label: 'Pet Shop', cat: 'Retail' },
    { label: 'Car Dealership', cat: 'Auto' },
    { label: 'Auto Repair Shop', cat: 'Auto' },
    { label: 'Car Wash', cat: 'Auto' },
    { label: 'Tire Shop', cat: 'Auto' },
    { label: 'Car Rental', cat: 'Auto' },
    { label: 'Plumber', cat: 'Home' },
    { label: 'Electrician', cat: 'Home' },
    { label: 'HVAC Services', cat: 'Home' },
    { label: 'Pest Control', cat: 'Home' },
    { label: 'Cleaning Service', cat: 'Home' },
    { label: 'Locksmith', cat: 'Home' },
    { label: 'Roofing Contractor', cat: 'Home' },
    { label: 'Landscaping Company', cat: 'Home' },
    { label: 'Moving Company', cat: 'Home' },
    { label: 'Solar Panel Installer', cat: 'Home' },
    { label: 'Travel Agency', cat: 'Travel' },
    { label: 'Hotel', cat: 'Travel' },
    { label: 'Event Management Company', cat: 'Events' },
    { label: 'Wedding Planner', cat: 'Events' },
    { label: 'Photography Studio', cat: 'Events' },
    { label: 'Video Production Company', cat: 'Events' },
    { label: 'DJ Services', cat: 'Events' },
    { label: 'Logistics Company', cat: 'B2B' },
    { label: 'Courier Service', cat: 'B2B' },
    { label: 'Staffing Agency', cat: 'B2B' },
    { label: 'Security Guard Service', cat: 'B2B' },
    { label: 'Co-working Space', cat: 'B2B' },
    { label: 'Printing Service', cat: 'B2B' },
    { label: 'Advertising Agency', cat: 'B2B' },
    { label: 'PR Agency', cat: 'B2B' },
];
